### ISSUE TITLE
Review?

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-lemminx#2]
It would be nice to get the code through review as it's quite non-standard compared to other ones (as it's Java-based). I would be interested to have a look at it and maybe make comments (not that I have any right now).

Could you create PR? Now that the code is in already, you could:
1) remove all files
2) commit 
3) push to master
4) Make a PR with reverted removal

@deathaxe

**Comment by deathaxe** [comment]
You are welcome to create issues with comments/suggestions or create PR's with proposed changes to discuss, but I don't think removing exiting and running code from the master once it got published is a good idea. We can go forward step by step but not backwards without critical reasons.

That said the package was created with an eye on LSP-json. There are some required changes as the server is not available via npm. So I can't follow your argument about "quite non-standard". Hope it's not because I am not a friend of defining constants which can be derived from the `__package__` normally or using a static class if only one instance is needed.

**Comment by rchl** [comment]
I didn't mean that it's doing things wrong when saying non-standard. Just different from what we've established and it was just interesting to have a look and maybe discuss some points.

But OK, you don't have to do what I've suggested. I can make issues for things I want to discuss (more work for me then ;)).
